### ISSUE TITLE
Failure to Load Shared Library

### ISSUE THREAD

**Issue by yaroto98** [hassio-addons/addon-matrix#24]
# Problem/Motivation
Just Upgraded to version 0.7.0 of this addon, and now the Matrix Server won't start
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior
When starting the container, I get the following error in the log (It's continuously repeating):

> [10:22:24] INFO: Starting Matrix Synapse...
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 69, in <module>
>     from synapse.server import HomeServer
>   File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 87, in <module>
>     from synapse.rest.media.v1.media_repository import (
>   File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/__init__.py", line 16, in <module>
>     import PIL.Image
>   File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 95, in <module>
>     from . import _imaging as core
> ImportError: Error loading shared library libtiff.so.5: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-arm-linux-gnueabihf.so)

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sea3pea0** [comment]
I am having the same exact problem on version 7.0 of this addon running on a intel nuc with linux mint 19.1 as the host os. When I revert back to a backup of version 5.2 that I have, everything works again. On another note, I was running version 7.0 on a different machine running (amd) ubuntu (can't remember if it was ubuntu 16.x or 18.x) and I wasn't getting that error

**Comment by yaroto98** [comment]
To clarify, I'm running this on the Raspberry Pi3, hassio fairly vanilla setup.

**Comment by viswa-swami** [comment]
I am getting the same error as well.. I am running hassio on docker on Ubuntu 18.04.. Matrix was working fine until it was updated to 0.7.0 (or rather the latest version)...  after updating, matrix addon restarted and it started throwing this error message..

**Comment by thundergreen** [comment]
Getting same error on version .07 and Linux Ubuntu 19.04 and hassio

```
[22:27:43] INFO: Config file at '/config/matrix.yaml' does not exist. Creating...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 69, in <module>
    from synapse.server import HomeServer
  File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 87, in <module>
    from synapse.rest.media.v1.media_repository import (
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/__init__.py", line 16, in <module>
    import PIL.Image
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 95, in <module>
    from . import _imaging as core
ImportError: Error loading shared library libtiff.so.5: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so)
[cont-init.d] synapse.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
