### ISSUE TITLE
Integration of Telegram and Whatsapp Bridges possible?

### ISSUE THREAD

**Issue by dasTholo** [hassio-addons/addon-matrix#31]
# Problem/Motivation

Integrate Whatsapp and Telegram Messenger

## Expected behavior

There are bridges for Matrix for [WhatsApp](https://github.com/tulir/mautrix-whatsapp) and [Telegram](https://github.com/tulir/mautrix-telegram). Is it possible to integrate these?

## Problems
I've tested with Matrix-Addon 0.7.3 , but i think problem Nr. 1 is the Port forwarding and 2. the nginx options.
But maybe another one can help me or us. So we can talk to telegram or whatsapp over our own Matrix in Hass.io.

## Proposed changes

1. Nginx Settings
 - many?
2. Port Options for Mautrix Whatsapp 
 - 29318:29318
3. Port Options for Mautrix-Telegram
- 29317:29317

Thx for your time!

**Comment by frenck** [comment]
This is out of scope for the add-on. The add-on is aiming to provide Matrix itself. You can always create separate add-ons for the bridges, we should not try to add them into a single add-on.
