### ISSUE TITLE
Issue when changing the server name in the configuration

### ISSUE THREAD

**Issue by the-mentor** [hassio-addons/addon-matrix#64]
# Issue when changing the server name in the configuration

The add-on fails to start with the following in the log
```
 You are running the latest version of this add-on.
 System: HassOS 4.11  (amd64 / qemux86-64)
 Home Assistant Core: 0.112.4
 Home Assistant Supervisor: 229
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] synapse.sh: executing... 
[19:32:25] FATAL: 
[19:32:25] FATAL: The server_name has changed!
[19:32:25] FATAL: Are you sure you want to do this?
[19:32:25] FATAL: If so, delete the "matrix.yaml" file located in "/config" and restart the addon.
[19:32:25] FATAL: WARNING: This will remove all rooms, users, chats and start afresh.
[cont-init.d] synapse.sh: exited 1.
```

## Expected behavior

The addon to start normally

## Actual behavior

addon stops with the above message in the log.

## Steps to reproduce

Install addon, change server name, start addon.

**Comment by kprestel** [comment]
I think this is intended. It is at the least documented:


>Option: server_name
>
>This is the hostname of your server. Set this to the host that you will be connecting to with your >clients without the port and without the http:// orhttps://. For example: if your domain name is home->assistant.io set your server_name to this.
>
>Note: You should only set this once. You will likely have to reinstall the addon to change this after >the fact, losing all your rooms and users.

Probably a restriction from the [upstream](https://github.com/matrix-org/synapse/blob/master/INSTALL.md#choosing-your-server-name).

**Comment by anoadragon453** [comment]
Indeed, a matrix server name cannot be changed once set up without wiping all data. If not already, this should be clearly stated during user setup so users are not caught surprised.

**Comment by iophobia** [comment]
Ran into this when I wanted to change access via DuckDNS. Sadly, un-/reinstalling the addon still yielded the same error as if the DB is not dropped during uninstall. Is that intended?

**Comment by anoadragon453** [comment]
I assume this is still an issue.

**Comment by anoadragon453** [comment]
This is likely still an issue btw :)
