### ISSUE TITLE
Vendored Synapse 1.14.0 has known vulns

### ISSUE THREAD

**Issue by bmbouter** [hassio-addons/addon-matrix#81]
# Problem/Motivation

The synapse vendored version 1.14.0 has known vulnerabilities. I was told this in the #synapse:matrix.org channel. The synapse version was determined by pointing https://federationtester.matrix.org at my installation and it reported 1.14.0.

## Expected behavior

To have the latest synapse version available, which right now is 1.23.0.

## Actual behavior

Version 1.14.0 was reported.

## Steps to reproduce

1. Install the add on
2. Open the 8443 port so outside connections can be made
3. Point https://federationtester.matrix.org/ at it and observe an out of date version of Synapse.

## Proposed changes

Upgrade Synapse

**Comment by frenck** [comment]
Already upgraded on dev: <https://github.com/hassio-addons/addon-matrix/blob/master/matrix/requirements.txt>
