### ISSUE TITLE
Cannot join matrix.org rooms with duckdns.org

### ISSUE THREAD

**Issue by bmbouter** [hassio-addons/addon-matrix#82]
# Problem/Motivation

As a matrix user with this add on as my homeserver, it would be great to join other matrix servers (federation). This works well ... unless you are a duckdns.org user, see this issue about SRV records and why https://github.com/matrix-org/synapse/issues/5882#issuecomment-523112566

## Expected behavior

When I go to list rooms on matrix.org, they list.

## Actual behavior

I get an error:  `Riot failed to get the public room list. Failed to find any key to satisfy VerifyJsonRequest`. Also in the add on logs when listing the rooms I see a `POST-12125 - {GET-O-5} [matrix.org] Got response headers: 401 Unauthorized`.

## Steps to reproduce

Use a duckdns.org domain to access your matrix add on. To to Explore -> select Matrix.org ... then receive the error

## Proposed changes

Use the other option of federation port discovery, which is to place a file at the `/.well-known/matrix/server` server location. This user resolved it [by doing that](https://github.com/matrix-org/synapse/issues/5882#issuecomment-626612264). The #synpase:matrix.org channel confirmed that is a perfectly viable approach also.

So somehow I need to have that file serve with my domain info in it. How can I have the add on enable this? If not enabled by default, having some docs on this being a known issue and how to configure this would be all I need.

**Comment by frenck** [comment]
This add-on does not support that, unfortunately. I do also have no plan on adding this behavior.

**Comment by bmbouter** [comment]
I'd like to contribute. How can I do the work needed to make this happen?

**Comment by bmbouter** [comment]
I imagine it would be a setting that the add on would interpret and then set the nginx response. I'm not that familiar with ingress yet, does this add on bring its own nginx reverse proxy or does hass itself handle that?

**Comment by frenck** [comment]
> I'd like to contribute. How can I do the work needed to make this happen?

I'm not willing to add that level of customization to this add-on.
