### ISSUE TITLE
Can't create server admin

### ISSUE THREAD

**Issue by AlexKnowsIt** [hassio-addons/addon-matrix#84]
# Problem/Motivation

I installed the Matrix Addon on hassio and everything worked fine so far until i realised, that I have no admin privileges on my server. I did not find any standard admins that are created at startup and it seems it has to be done inside the docker container itself.
`sudo register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml https://127.0.0.1:8448`

## Expected behavior

I tried to create a community with my created user. 

## Actual behavior

The server replied, that this is just possible with admin privileges.

## Proposed changes

Either there is a standard admin user created at first startup of the addon or there is an option in the matrix.yaml file, where users can be changed. With four variables (name, email, password (not necessary), and an admin field that can be set to true or false) every user than could get leveraged rights.

**Comment by GoSpursGoNL** [comment]
I have the same issue. In addition, after following the addon instructions, it is not clear to me how to manage the Matrix server. Where the config file (if any) is located for example. As it seems by default various things are disabled, f.i:
Adding phone numbers to user account is not supported by this homeserver (Status 400)
